apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: captaingab/qr-code-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: AZURE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_CONTAINER_NAME

