apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9cmlzaGFicHJvamVjdHM7QWNjb3VudEtleT1aK1JoOHZDWWI1WkFKZjR4eGhQMVpRajkxTWVKNjZTeWxtdnFoNkdUNCs4ZDdCZ1VNQnJkK05JY2RZeTI1bUlRQ1FxeXNIdGlzZ0V0K0FTdG82TjJvUT09O0Jsb2JFbmRwb2ludD1odHRwczovL3Jpc2hhYnByb2plY3RzLmJsb2IuY29yZS53aW5kb3dzLm5ldC87RmlsZUVuZHBvaW50PWh0dHBzOi8vcmlzaGFicHJvamVjdHMuZmlsZS5jb3JlLndpbmRvd3MubmV0LztRdWV1ZUVuZHBvaW50PWh0dHBzOi8vcmlzaGFicHJvamVjdHMucXVldWUuY29yZS53aW5kb3dzLm5ldC87VGFibGVFbmRwb2ludD1odHRwczovL3Jpc2hhYnByb2plY3RzLnRhYmxlLmNvcmUud2luZG93cy5uZXQv
  AZURE_CONTAINER_NAME: ZGV2b3BzLXFyMQ==